workflow fix + green
test deploy with green

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -129,7 +129,7 @@ jobs:
         echo "ROUTE=$ROUTE" >> $GITHUB_ENV
     - name: View Application Route
       run: |
-        [[ -n ${{ env.ROUTE }} ]] || echo "Determining application route failed in previous step"; exit 1
+        [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
         echo "======================== Your application is available at: ========================"
         echo ${{ env.ROUTE }}
         echo "==================================================================================="
